import { z } from 'zod';

/**
 * Zod schemas for Module 8 (AI Legal Chat) — File 149.
 *
 * ARCHITECTURAL NOTE, DEPARTURE FROM FILES 101-141's PATTERN: every prior
 * Phase 2 schema file (risk-detection, missing-clause-detection,
 * compliance-detection, ai-recommendation, legal-health-score,
 * ai-legal-insight) validates AI-GENERATED structured output — the shape
 * passed as AIGenerationRequest.schema to generateStructured(), then
 * stored as a single JSON blob in a `result` column on a run-lifecycle
 * row (pending -> processing -> completed/failed).
 *
 * Chat has no equivalent. There is no single "run" producing one result
 * blob — a conversation is an open-ended sequence of individually-inserted
 * rows. Chat responses go through generateStreamingText() (Provider Layer
 * streaming amendment), which returns raw text deltas, not a
 * Zod-validated object. There is therefore no AI-output schema for this
 * module.
 *
 * What this file validates instead is USER INPUT at the Route boundary —
 * starting a conversation, and sending a message. Closer in spirit to
 * early request-validation schemas (File 24, profiles) than to the
 * Files 101-141 AI-result-schema pattern.
 */

/**
 * Mirrors the migration's `check (role in ('user', 'assistant'))`
 * constraint exactly (File 148). Deliberately duplicated as a single
 * source of truth between the Postgres constraint and this Zod enum,
 * same convention every prior module's status/severity enums already
 * follow.
 */
export const ChatMessageRole = z.enum(['user', 'assistant']);
export type ChatMessageRole = z.infer<typeof ChatMessageRole>;

/**
 * Input required to start a new conversation. Single-document scope
 * (confirmed decision) — every conversation is anchored to exactly one
 * document analysis, matching every prior module's document_analysis_id
 * FK pattern.
 *
 * No `title` field accepted here — title-generation strategy is an open
 * item flagged in File 148, not yet decided. Left out of the input
 * schema entirely rather than accepted-but-unused, so this schema does
 * not silently assert a decision that hasn't been made.
 */
export const createChatConversationInputSchema = z.object({
  documentAnalysisId: z
    .string()
    .uuid()
    .describe('The document analysis this conversation is anchored to. Single-document scope — one conversation cannot span multiple analyses.'),
});
export type CreateChatConversationInput = z.infer<typeof createChatConversationInputSchema>;

/**
 * Input required to send a message into an existing conversation.
 *
 * KEY DECISION, NEW JUDGMENT CALL — content is capped at 4000 characters.
 * None of the four prior synthesis modules needed an input length bound;
 * their only user-supplied input was a document_analysis_id FK, with all
 * substantive content generated by the AI model. Chat is the first module
 * where a user directly authors unbounded free text, so this is a fresh
 * decision, not inherited precedent. The number itself is provisional —
 * flagged as adjustable, not asserted as final.
 *
 * `.min(1)` rejects empty/whitespace-only messages at the schema layer
 * rather than relying on the Service or a database NOT NULL constraint
 * alone to catch it.
 */
export const sendMessageInputSchema = z.object({
  conversationId: z
    .string()
    .uuid()
    .describe('The conversation this message belongs to.'),
  content: z
    .string()
    .trim()
    .min(1, 'Message content cannot be empty.')
    .max(4000, 'Message content cannot exceed 4000 characters.')
    .describe('The user-authored message text.'),
});
export type SendMessageInput = z.infer<typeof sendMessageInputSchema>;
